apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jhfy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jhfy
    app.kubernetes.io/part-of: ci10t-786-0081-app
  name: devfile-sample-jhfy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jhfy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jhfy
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0081-tenant/ci10t-786-0081-app/devfile-sample-jhfy@sha256:42c027e97107aa75772b9d239faebdcc3e06fc913b993a73224e222c254fe19a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
