apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jhfy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0081-tenant/ci10t-786-0081-app/devfile-sample-jhfy@sha256:42c027e97107aa75772b9d239faebdcc3e06fc913b993a73224e222c254fe19a
        name: my-nodejs
        resources: {}
status: {}
